### ISSUE TITLE
What is this repo licensed under?

### ISSUE THREAD

**Issue by zaataravi** [waf/waf.github.com#1]
Hi there, @waf - I'm interested in re-using this repo for my own personal blog. However, I can't find a license in the repo. Can you clarify if it's OK to re-use, or if you prefer it is not? thank you! --r.

**Comment by waf** [comment]
Hi @ravi-sensify, thanks for checking. I've added a license to the repo.

This site is generated using the [Acrylamid static site generator](https://github.com/posativ/acrylamid).

Assuming you're interested in the design assets of this blog, those are licensed under the MIT license. You're free to re-use and modify it, but I'd appreciate it if there was attribution somewhere on your site.

The content is licensed as creative commons, but I'm assuming you're not interested in putting that on your personal blog :)

**Comment by zaataravi** [comment]
@waf - thank you, kindly! Yes, I'll attribute back to you, and no, I don't care for comments ;)

**Comment by zaataravi** [comment]
@waf: Please let me know if the credits do not look OK: https://ravi.rao.li/

**Comment by waf** [comment]
Looks great, thanks for the credits! I'm fine if you want to make them less prominent, too.
